export const SIGN_IN = "SIGN_IN";
export const LOG_OUT = "LOG_OUT";
export const UPDATE_TOKENS = "UPDATE_TOKENS";
export const INCREMENT_FOLLOWERS = "INCREMENT_FOLLOWS";
export const DECRIMENT_FOLLOWERS = "DECRIMENT_FOLLOWERS";
export const INCREMENT_FOLLOWINGS = "INCREMENT_FOLLOWINGS";
export const DECRIMENT_FOLLOWINGS = "DECRIMENT_FOLLOWINGS";
export const ADD_USER = "ADD_USER";

export const ADD_FOLLOWERS = "ADD_FOLLOWERS";
export const INIT_FOLLOWERS = "INIT_FOLLOWERS";
export const TOGGLE_FOLLOW = "TOGGLE_FOLLOW";
export const INIT_FOLLOWINGS = "INIT_FOLLOWINGS";
export const TOGGLE_FOLLOWING = "TOGGLE_FOLLOWING";
export const INIT_PROFILE = "INIT_PROFILE";
export const TOGGLE_FOLLOW_GLOBAL = 'TOGGLE_FOLLOW_GLOBAL';

export const INIT_POSTS = 'INIT_POSTS';
export const LOAD_MORE_POSTS = 'LOAD_MORE_POSTS';

