export const SIGN_IN = "SIGN_IN";
export const LOG_OUT = "LOG_OUT";
export const UPDATE_TOKENS = "UPDATE_TOKENS";
export const INCREMENT_FOLLOWERS = "INCREMENT_FOLLOWS";
export const DECRIMENT_FOLLOWERS = "DECRIMENT_FOLLOWERS";
export const INCREMENT_FOLLOWINGS = "INCREMENT_FOLLOWINGS";
export const DECRIMENT_FOLLOWINGS = "DECRIMENT_FOLLOWINGS";
export const ADD_USER = "ADD_USER";
